// Note: this file was generated by the build process. See README.md in src/ for details.

const imageSpriteConfig = {
  '/arrow-left.png': [
    862,
    184,
    6,
    10
  ],
  '/arrow-right.png': [
    870,
    184,
    6,
    10
  ],
  '/balloon_mac.png': [
    420,
    0,
    76,
    288
  ],
  '/banana.png': [
    820,
    653,
    32,
    38
  ],
  '/barb-wire.png': [
    592,
    711,
    36,
    22
  ],
  '/base-sprite-burning.png': [
    81,
    267,
    204,
    128
  ],
  '/base-sprite-enemy.png': [
    0,
    0,
    208,
    265
  ],
  '/base-sprite.png': [
    210,
    0,
    208,
    265
  ],
  '/bomb.png': [
    854,
    170,
    28,
    12
  ],
  '/bunker-burning-sprite.png': [
    309,
    519,
    106,
    72
  ],
  '/bunker-dead.png': [
    688,
    602,
    106,
    18
  ],
  '/bunker_mac.png': [
    206,
    711,
    104,
    51
  ],
  '/cactus.png': [
    854,
    70,
    24,
    34
  ],
  '/cactus2.png': [
    458,
    290,
    36,
    50
  ],
  '/chain.png': [
    854,
    184,
    6,
    12
  ],
  '/checkmark-grass.png': [
    852,
    250,
    30,
    20
  ],
  '/cloud-1.png': [
    0,
    711,
    204,
    58
  ],
  '/cloud-2.png': [
    0,
    653,
    232,
    56
  ],
  '/cloud-3.png': [
    632,
    0,
    250,
    68
  ],
  '/end-bunker-enemy.png': [
    652,
    653,
    82,
    38
  ],
  '/end-bunker.png': [
    736,
    653,
    82,
    38
  ],
  '/engineer-enemy-sprite-horizontal.png': [
    780,
    622,
    100,
    22
  ],
  '/engineer-sprite-horizontal.png': [
    309,
    593,
    100,
    22
  ],
  '/explosion-large-2.png': [
    81,
    397,
    112,
    220
  ],
  '/explosion-large.png': [
    195,
    397,
    112,
    220
  ],
  '/explosion-shrapnel-2.png': [
    0,
    267,
    79,
    384
  ],
  '/explosion-shrapnel.png': [
    632,
    370,
    54,
    250
  ],
  '/explosion-spark-2.png': [
    854,
    198,
    5,
    5
  ],
  '/explosion-spark.png': [
    861,
    198,
    5,
    5
  ],
  '/flower-bush.png': [
    164,
    771,
    36,
    26
  ],
  '/flower.png': [
    854,
    152,
    22,
    16
  ],
  '/flowers.png': [
    420,
    566,
    68,
    22
  ],
  '/generic-explosion-2.png': [
    498,
    162,
    110,
    180
  ],
  '/generic-explosion.png': [
    498,
    344,
    110,
    180
  ],
  '/grass.png': [
    796,
    602,
    80,
    18
  ],
  '/grave-cross.png': [
    854,
    130,
    26,
    20
  ],
  '/gravestone.png': [
    550,
    711,
    40,
    24
  ],
  '/gravestone2.png': [
    852,
    224,
    30,
    24
  ],
  '/helicopter-enemy-sprite.png': [
    632,
    70,
    110,
    152
  ],
  '/helicopter-rotating-enemy.png': [
    498,
    526,
    100,
    120
  ],
  '/helicopter-rotating.png': [
    309,
    397,
    100,
    120
  ],
  '/helicopter-sprite.png': [
    287,
    267,
    100,
    128
  ],
  '/infantry-enemy-sprite-horizontal.png': [
    81,
    619,
    110,
    22
  ],
  '/infantry-sprite-horizontal.png': [
    193,
    619,
    110,
    22
  ],
  '/landing-pad-sprite.png': [
    0,
    771,
    162,
    66
  ],
  '/medal-1.png': [
    420,
    590,
    33,
    40
  ],
  '/medal-2.png': [
    455,
    590,
    33,
    40
  ],
  '/medal-3.png': [
    410,
    711,
    33,
    40
  ],
  '/medal-4.png': [
    445,
    711,
    33,
    40
  ],
  '/medal-5.png': [
    480,
    711,
    33,
    40
  ],
  '/medal-6.png': [
    515,
    711,
    33,
    40
  ],
  '/missile-launcher-enemy.png': [
    744,
    70,
    108,
    144
  ],
  '/missile-launcher.png': [
    632,
    224,
    108,
    144
  ],
  '/palm-tree.png': [
    458,
    342,
    36,
    44
  ],
  '/parachute-infantry-enemy.png': [
    368,
    653,
    140,
    40
  ],
  '/parachute-infantry.png': [
    510,
    653,
    140,
    40
  ],
  '/right-arrow-sign-mac.png': [
    420,
    476,
    56,
    50
  ],
  '/rock.png': [
    202,
    771,
    36,
    26
  ],
  '/rock2.png': [
    854,
    106,
    26,
    22
  ],
  '/rubber-chicken-96.png': [
    312,
    711,
    96,
    48
  ],
  '/sand-dune.png': [
    305,
    619,
    102,
    16
  ],
  '/sand-dunes.png': [
    632,
    622,
    146,
    22
  ],
  '/shrapnel-glow.png': [
    498,
    0,
    132,
    160
  ],
  '/smart-missile.png': [
    852,
    272,
    30,
    8
  ],
  '/smoke-sprite-glow.png': [
    742,
    224,
    108,
    144
  ],
  '/super-bunker_mac.png': [
    234,
    653,
    132,
    56
  ],
  '/tank-enemy-sprite.png': [
    688,
    370,
    116,
    114
  ],
  '/tank-sprite.png': [
    688,
    486,
    116,
    114
  ],
  '/tank_flame.png': [
    420,
    528,
    64,
    36
  ],
  '/tree.png': [
    420,
    420,
    52,
    54
  ],
  '/tumbleweed.png': [
    458,
    388,
    36,
    30
  ],
  '/turret-sprite.png': [
    420,
    290,
    36,
    128
  ],
  '/van-enemy.png': [
    806,
    370,
    76,
    96
  ],
  '/van.png': [
    806,
    486,
    76,
    96
  ]
};

export { imageSpriteConfig };